name: Build macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install nasm
        run: brew install nasm
      - name: Compile FFmpeg
        run: cd ${{github.workspace}}/extern/FFmpeg && mkdir build && ./configure --prefix=$(pwd)/build  --disable-doc --disable-programs --disable-static --enable-shared && make -j8 && make install
      - name: Configure CMake
        run: cmake . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DFFmpeg_INCLUDE=${{github.workspace}}/extern/FFmpeg/build/include -DFFmpeg_LIB=${{github.workspace}}/extern/FFmpeg/build/lib
      - name: Build
        run: cmake --build ${{github.workspace}}/build -j 8 --config ${{matrix.configuration}}
